//
// Created by admin on 9/28/2023.
//

#ifndef ARDALIVEMEDIASERVER_POSTRESOURCEHANDLER_HPP
#define ARDALIVEMEDIASERVER_POSTRESOURCEHANDLER_HPP

class PostResourceHandler
{
};

#endif // ARDALIVEMEDIASERVER_POSTRESOURCEHANDLER_HPP
